### ISSUE TITLE
Support Kafka 3+ by upgrading Sarama

### ISSUE THREAD

**Issue by EladLeev** [EladLeev/kafka-config-metrics#15]
- [x] Upgrade Sarama from [`v1.26.4`](https://github.com/EladLeev/kafka-config-metrics/blob/master/go.mod#L7) to latest.
- [x] Make sure Kafka 3+ is working well.

**Comment by scpsx** [comment]
Works with Kafka version 3.2.0 👍

**Comment by EladLeev** [comment]
Thanks for the input @scpsx
